### ISSUE TITLE
Mechanism to bypass proxy for iframes

### ISSUE THREAD

**Issue by murb-cognella** [hypothesis/viahtml#457]
While using Hypothesis via LTI in Moodle, I'm trying to load an iframe from my originating LMS that preserves a user session. I have content that doesn’t play well with being annotated – H5P, basically interactive widgets – and I'm trying to interleave it with regular text. So the flow is:
1. Source LMS, has a module that loads…
2. Hypothesis, via LTI 1.3, which points to…
3. Pressbooks, which holds content interleaved with…
4. iframes pointing back to H5P content hosted in the LMS from item 1 above.

I'd like to indicate to viahtml not to proxy certain iframes. If could set an attribute on an iframe, like `data-h-no-proxy`, that would hint to hypothesis not to proxy the source, I think that would do what we need.

**Comment by robertknight** [comment]
> While using Hypothesis via LTI in Moodle, I'm trying to load an iframe from my originating LMS that preserves a user session.

In some browsers you might run into problems preserving the user session in cases where the iframe is from a different origin than the top-level tab. The problem is that third-party iframes look the same as ads to browsers and are subjected to tracking protection measures. [`requestStorageAccess`](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess) can I believe be used to regain session access, but only in response to a user gesture.

**Comment by murb-cognella** [comment]
Hi Robert – for our particular case, we will be controlling the top-level origin as well. We might be in trouble if we open the LTI app in a new window, but I think we will be alright if we embed it?
